install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyverse")
install.packages("tigris")
install.packages("ggrepel")
install.packages("arules")
install.packages("arulesViz")
install.packages("randomForest")