---
title: "Plots"
author: "Kapil Parab/Nicaise Irambona"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importing libraries

```{r}
library(sf)
library(tigris)
library(tidyverse)
```

```{r}
# Getting city outlines for Arizona
arizona_city_outline <- st_read("data/arizona_city_boundary/arizona_city.shp") %>%
  st_transform(., crs = 4326)

# Getting Arizona state shape file
az_counties <- counties("AZ", year = 2024) %>% st_transform(., crs = 4326)

az_road <- primary_secondary_roads("AZ", year = 2024) %>% st_transform(., crs = 4326)
```
# Reading dataset

```{r}

vehicles <-
    list.files(path = "./data/cleansed/vehicles/", pattern = "*.csv", full.names = TRUE) %>% 
    map_df(~read_csv(., show_col_types = FALSE))

motorcycles <-
    list.files(path = "./data/cleansed/motorcycles/", pattern = "*.csv", full.names = TRUE) %>% 
    map_df(~read_csv(., show_col_types = FALSE))

```

```{r}
crash_moto <- motorcycles %>%
  filter(., STATE == "Arizona") %>%
  select(CASE_ID, ACC_TS, VEH_BRAND, LATITUDE, LONGITUDE) %>% distinct()

crash_veh <- vehicles %>%
  filter(., STATE == "Arizona") %>%
  select(CASE_ID, ACC_TS, VEH_CATEGORY, LATITUDE, LONGITUDE) %>% distinct()


```


```{r}
az_city_labels <- tail(
  arizona_city_outline[order(arizona_city_outline$Shape__Are),],
  5
)
```


```{r}
ggplot() + 
  geom_sf(data = az_counties, fill = "white") +
  geom_sf(data = arizona_city_outline, fill = "grey") +
  geom_sf(data = az_road, fill = "green") +
  geom_point(data = crash_veh, aes(x = LONGITUDE, y = LATITUDE), size = 1, color = alpha("red", 0.2)) +
  geom_label_repel(
    data = az_city_labels,
    aes(label = Name, geometry = geometry),
    stat = "sf_coordinates",
    size = 2,
    min.segment.length = 0
  ) +
  labs(title = "Vehicle Crashes in Arizona", subtitle = "2020-2022") + coord_sf() +
  theme(axis.title = element_blank(), axis.ticks = element_blank())
```

```{r}
ggplot() + 
  geom_sf(data = az_counties, fill = "white") +
  geom_sf(data = arizona_city_outline, fill = "grey") +
  geom_sf(data = az_road, fill = "green") +
  geom_point(data = crash_moto, aes(x = LONGITUDE, y = LATITUDE), size = 1, color = alpha("red", 0.2)) +
  geom_label_repel(
    data = az_city_labels,
    aes(label = Name, geometry = geometry),
    stat = "sf_coordinates",
    size = 2,
    min.segment.length = 0
  ) +
  labs(title = "Motorcycle Crashes in Arizona", subtitle = "2020-2022") + coord_sf() +
  theme(axis.title = element_blank(), axis.ticks = element_blank())
```

```{r}
# Vehicle crashes over years
crash_veh_yr <- crash_veh %>% mutate(ACC_YEAR = year(ACC_TS)) %>%
  select(ACC_YEAR, VEH_CATEGORY) %>%
  group_by(ACC_YEAR, VEH_CATEGORY) %>%
  summarise(total_count = n()) %>%
  filter(., VEH_CATEGORY != "Unknown") %>%
  slice_max(order_by = total_count, n = 10)

ggplot(crash_veh_yr, aes(x = VEH_CATEGORY, y = total_count, fill = VEH_CATEGORY)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  theme(legend.position = "none", axis.title.y = element_blank()) +
  facet_grid(. ~ ACC_YEAR)
```

```{r}
# Vehicle crashes over years
crash_moto_yr <- crash_moto %>% mutate(ACC_YEAR = year(ACC_TS)) %>%
  select(ACC_YEAR, VEH_BRAND) %>%
  group_by(ACC_YEAR, VEH_BRAND) %>%
  summarise(total_count = n(), .groups = "drop") %>%
  filter(., VEH_BRAND != "Unknown") %>%
  group_by(ACC_YEAR) %>%
  slice_max(order_by = total_count, n = 10)

ggplot(crash_moto_yr, aes(x = VEH_BRAND, y = total_count, fill = VEH_BRAND)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  theme(legend.position = "none", axis.title.y = element_blank()) +
  facet_grid(. ~ ACC_YEAR)
```

```{r}
crash_veh_hr <- crash_veh %>% mutate(ACC_HR = hour(ACC_TS)) %>%
  select(ACC_HR) %>%
  mutate(CAT = "Vehicles") %>%
  group_by(ACC_HR, CAT) %>%
  summarise(total_count = n())

crash_moto_hr <- crash_moto %>% mutate(ACC_HR = hour(ACC_TS)) %>%
  select(ACC_HR) %>%
  mutate(CAT = "Motorcycles") %>%
  group_by(ACC_HR, CAT) %>%
  summarise(total_count = n())

hr_merge <- merge(crash_veh_hr, crash_moto_hr, all = TRUE)

ggplot(data = hr_merge, aes(x = ACC_HR, y = total_count, group = CAT, color = CAT)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = 0:23, name = "Hour") +
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100, 150, 200, 250, 300, 350, 400, 450, 500), name = "Count") +
  labs(y = "Total Count", color = "Category") +
  theme_minimal() +
  theme(
    legend.position = "inside", 
    legend.direction = "horizontal",
    legend.title.position = "top",
    legend.position.inside = c(0.19, 0.9),
    legend.background = element_rect(fill = "lightgrey"),
    axis.line = element_blank(),
    panel.grid.minor = element_blank()
    ) + 
  labs(
    title = "Accidents in Arizona based on Time of Day", subtitle = "2020-2022"
  )
```

```{r}
crash_veh_dt <- crash_veh %>% mutate(ACC_DATE = day(ACC_TS)) %>%
  select(ACC_DATE) %>%
  mutate(CAT = "Vehicles") %>%
  group_by(ACC_DATE, CAT) %>%
  summarise(total_count = n())

crash_moto_dt <- crash_moto %>% mutate(ACC_DATE = day(ACC_TS)) %>%
  select(ACC_DATE) %>%
  mutate(CAT = "Motorcycles") %>%
  group_by(ACC_DATE, CAT) %>%
  summarise(total_count = n())

dt_merge <- merge(crash_veh_dt, crash_moto_dt, all = TRUE)

`ggplot(data = dt_merge, aes(x = ACC_DATE, y = total_count, group = CAT, color = CAT)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = 1:31, name = "Day") +
  scale_y_continuous(breaks = c(0, 50, 100, 150, 200, 250), name = "Count") +
  labs(y = "Total Count", color = "Category") +
  theme_bw() +
  theme(
    legend.position = "right", 
    legend.direction = "vertical",
    legend.title.position = "top",
    legend.position.inside = c(0.19, 0.9),
    legend.background = element_rect(fill = "lightgrey"),
    axis.line = element_blank(),
    panel.grid.minor.x = element_blank()
    ) + 
  labs(
    title = "Accidents in Arizona based on Day of Month", subtitle = "2020-2022"
  )`
```
