---
title: "Random Forest"
author: "Kapil Parab/Nicaise Irambona"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importing libraries

```{r}
library(tidyverse)
library(randomForest)
library(caret)
```

# Reading dataset

```{r}

vehicles <-
    list.files(path = "./data/cleansed/vehicles/", pattern = "*.csv", full.names = TRUE) %>% 
    map_df(~read_csv(., show_col_types = FALSE))

motorcycles <-
    list.files(path = "./data/cleansed/motorcycles/", pattern = "*.csv", full.names = TRUE) %>% 
    map_df(~read_csv(., show_col_types = FALSE))

```

```{r}
vehicles_sub <- vehicles %>% within(., rm("CASE_ID", "STATE", "COUNTY", "VEH_MOD_YEAR", "VEH_BRAND", "VEH_MODEL", "LATITUDE", "LONGITUDE", "ACC_TS", "AIRBAG_DEPLOYED")) 

vehicles_sub$AGE <- cut(vehicles_sub$AGE, 
      breaks = c(0, 5, 12, 18, 35, 50, 65, Inf), 
      labels = c("Infant", "Child", "Teen", "Adult", "Adult", "Senior", "Elderly"),
      include.lowest = TRUE
)

vehicles_sub <- vehicles_sub %>%
  mutate(
    DRINKING_FLAG = case_when(
      AGE != "Child" & 
        PERSON_TYPE == "Driver" & 
        DRINKING_FLAG == "Not Reported" ~ "Maybe",
      .default = DRINKING_FLAG
    ),
    DRUGS_FLAG = case_when(
      AGE != "Child" & 
        PERSON_TYPE == "Driver" & 
        DRUGS_FLAG == "Not Reported" ~ "Maybe",
      .default = DRUGS_FLAG
    ),
    ROLLOVER = ifelse(is.na(ROLLOVER), "Maybe", ROLLOVER)
  )

vehicles_sub$INJURY <- as.factor(vehicles_sub$INJURY)
```

```{r}
# Split the data into training and testing sets
set.seed(420)  # For reproducibility
train_index <- createDataPartition(vehicles_sub$INJURY, p = 0.8, list = FALSE)
train_data <- vehicles_sub[train_index, ]
test_data <- vehicles_sub[-train_index, ]
```

```{r}
# Best Random Forest Model. Grid Search Results
rf_model <- randomForest(INJURY ~ ., data = train_data, ntree = 500, mtry = 4, nodesize = 1, sampsize = floor(0.7 * nrow(train_data)), importance = TRUE)

# View model summary
print(rf_model)
```

```{r}
# Predict on test data
predictions <- predict(rf_model, test_data)

# Evaluate the model
conf_matrix <- confusionMatrix(predictions, test_data$INJURY)
print(conf_matrix)
```

```{r}
# Variable importance plot
varImpPlot(rf_model)
```