---
title: "Apriori"
author: "Kapil Parab/Nicaise Irambona"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importing libraries

```{r}
library(tidyverse)
library(arules)
library(arulesViz)
```

# Reading dataset

```{r}

vehicles <-
    list.files(path = "./data/cleansed/vehicles/", pattern = "*.csv", full.names = TRUE) %>% 
    map_df(~read_csv(., show_col_types = FALSE))

motorcycles <-
    list.files(path = "./data/cleansed/motorcycles/", pattern = "*.csv", full.names = TRUE) %>% 
    map_df(~read_csv(., show_col_types = FALSE))

```

# Vehicles

```{r}
vehicles_sub <- vehicles %>% 
  filter(., 
        DRINKING_FLAG != "Not Reported" & 
          PERSON_TYPE == "Driver"
  ) %>%
  within(., rm("CASE_ID", "STATE", "COUNTY", "VEH_MOD_YEAR", "VEH_BRAND", "VEH_MODEL", "LATITUDE", "LONGITUDE", "ACC_TS", "DRUGS_FLAG", "SEAT_POS", "PERSON_TYPE"))

vehicles_sub$AGE <- cut(vehicles_sub$AGE, 
      breaks = c(0, 5, 12, 18, 35, 50, 65, Inf), 
      labels = c("Infant", "Child", "Teen", "Adult", "Adult", "Senior", "Elderly"),
      include.lowest = TRUE
)

vehicles_sub <- data.frame(lapply(vehicles_sub, as.factor))
```

```{r}
transactions <- as(vehicles_sub, "transactions")

# Run Apriori algorithm
rules <- apriori(transactions,
  parameter = list(supp = 0.01, conf = 0.8, target = "rules"),
  appearance = list(rhs = c("INJURY=Death"), default = "lhs")
)

# View the rules
inspect(rules)
```

```{r}
# Filter rules with high lift
veh_high_lift_rules <- subset(rules, lift > 1.5)
```

```{r}
# Scatter plot
plot(veh_high_lift_rules, method = "scatterplot", measure = c("support", "confidence"), shading = "lift", main = "Scatterplot of Rules")
```

```{r}
# Rule Graph
plot(veh_high_lift_rules, method = "graph", engine = "htmlwidget", main = "Graph of Rules", max = 20)
```

# Motorcycles

```{r}
moto_sub <- motorcycles %>% 
  filter(., 
        DRINKING_FLAG != "Not Reported" & DRUGS_FLAG != "Not Reported" & SEAT_POS == "Rider"
  ) %>%
  within(., rm("CASE_ID", "STATE", "COUNTY", "VEH_MOD_YEAR", "VEH_BRAND", "VEH_MODEL", "VEH_CATEGORY", "LATITUDE", "LONGITUDE", "ACC_TS", "SEAT_POS"))


moto_sub$AGE <- cut(moto_sub$AGE, 
      breaks = c(0, 5, 12, 18, 35, 50, 65, Inf), 
      labels = c("Infant", "Child", "Teen", "Adult", "Adult", "Senior", "Elderly"),
      include.lowest = TRUE
)

moto_sub <- data.frame(lapply(moto_sub, as.factor))
```

```{r}
transactions <- as(moto_sub, "transactions")

# Run Apriori algorithm
rules <- apriori(transactions,
  parameter = list(supp = 0.01, conf = 0.8, target = "rules"),
  appearance = list(rhs = c("INJURY=Death"), default = "lhs")
)

# View the rules
inspect(rules)
```

```{r}
# Filter rules with high lift
moto_high_lift_rules <- subset(rules, lift > 1)
```

```{r}
# Scatter plot
plot(moto_high_lift_rules, method = "scatterplot", measure = c("support", "confidence"), shading = "lift", main = "Scatterplot of Rules")
```

```{r}
# Rule Graph
plot(moto_high_lift_rules, method = "graph", engine = "htmlwidget", main = "Graph of Rules", max = 20)
```

